PAGE_MAPPING = {
    '/_b_a_c_k_e_n_d/Milestone/therapy-reports/?(\?.*)?$':'MDC-API-THR',
    '/_b_a_c_k_e_n_d/Milestone/get_patient_assessments/?(\?.*)?$':'MDC-API-GAS',
    '/_b_a_c_k_e_n_d/Milestone/others-reports/?(\?.*)?$':'MDC-API-RTS',
    '/_b_a_c_k_e_n_d/Milestone/get-latest-billing-no/':'MDC-API-LBN',
    '/_b_a_c_k_e_n_d/Milestone/get-consulting-doctors/':'MDC-API-CDR',
    '/_b_a_c_k_e_n_d/Milestone/save-consulting-doctor/':'MDC-P-ASM',
    '/_b_a_c_k_e_n_d/Milestone/save-assessments/':'MDC-P-ASM',
    '/_b_a_c_k_e_n_d/Milestone/others_billing/':'MDC-P-OSB',
    '/_b_a_c_k_e_n_d/Milestone/all-patient/?(\?.*)?$':'MDC-API-PAT',
    '/_b_a_c_k_e_n_d/Milestone/pendingPayment/':'MDC-P-PNP',
    '/_b_a_c_k_e_n_d/Milestone/updatePayment/':'MDC-P-PNP',
    '/_b_a_c_k_e_n_d/Milestone/next-registration-number/':'MDC-P-REG',
    '/_b_a_c_k_e_n_d/Milestone/referral-doctor/list/':'MDC-API-RDL',
    '/_b_a_c_k_e_n_d/Milestone/referral-doctor/register/':'MDC-P-REG',
    '/_b_a_c_k_e_n_d/Milestone/register/':'MDC-P-REG',
    '/_b_a_c_k_e_n_d/Milestone/referrals/?(\?.*)?$':'MDC-P-SOR',
    '/_b_a_c_k_e_n_d/Milestone/therapy_billing/':'MDC-P-TRB',
    '/_b_a_c_k_e_n_d/Milestone/update-patient/.*':'MDC-P-PTE',
    '/_b_a_c_k_e_n_d/Milestone/update-doctor(?:/[^/]+)+/$':'MDC-P-RDE',
    '/_b_a_c_k_e_n_d/Milestone/update-employeeDr(?:/[^/]+)+/$':'MDC-P-CDE',
    
    #attendance
    '/_b_a_c_k_e_n_d/Milestone/pending-payments/':'MDC-P-PNPR',
    '/_b_a_c_k_e_n_d/Milestone/get_all_patient_details/':'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/attendance/':'MDC-API-AT',
    r'^/_b_a_c_k_e_n_d/Milestone/all-attendance-patient/?(\?.*)?$': 'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/add_patient_attendance/':'MDC-API-AT',
    r'^/_b_a_c_k_e_n_d/Milestone/get_all_patient_attendance/?(\?.*)?$': 'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/edit_patient_attendance/':'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/delete_patient_attendance/':'MDC-API-AT',
    "/_b_a_c_k_e_n_d/Milestone/get_all_patient_details/":'MDC-API-AT',
    
    "/_b_a_c_k_e_n_d/Milestone/get_pending_attendance_requests/":'MDC-API-ADM',
    "/_b_a_c_k_e_n_d/Milestone/attendance-update/":'MDC-API-ADM',
    "/_b_a_c_k_e_n_d/Milestone/all-patient-filterless/":'MDC-API-PDC',
    "/_b_a_c_k_e_n_d/Milestone/HistoryRecordingSheet/":'MDC-API-PDC',
    "/_b_a_c_k_e_n_d/Milestone/GetHistoryRecordingSheet/":'MDC-API-PDC',
    r'^/_b_a_c_k_e_n_d/Milestone/GetHistoryRecordingSheetbyRegNO/?(\?.*)?$': 'MDC-API-PDC',
    r'/_b_a_c_k_e_n_d/Milestone/UpdateHistoryRecordingSheet/?(\?.*)?$':"MDC-API-PDC",

    "/_b_a_c_k_e_n_d/Milestone/update_attendance_sessions/":'MDC-API-AT',
    r'^/_b_a_c_k_e_n_d/Milestone/get_all_patient_oldattendance/?(\?.*)?$': 'MDC-API-AT',
    
    r'^/_b_a_c_k_e_n_d/Milestone/get_ot_patients/?(\?.*)?$':'MDC-P-GOP',
    r'^/_b_a_c_k_e_n_d/Milestone/get_speech_patients/?(\?.*)?$':'MDC-P-GSP',
    r'^/_b_a_c_k_e_n_d/Milestone/get_pt_patients/?(\?.*)?$':'MDC-P-GPP',
    r'^/_b_a_c_k_e_n_d/Milestone/get_psychological_patients/?(\?.*)?$':'MDC-P-GCP',
    r'^/_b_a_c_k_e_n_d/Milestone/get_all_category_patients/?(\?.*)?$':'MDC-P-GAP',
    r'^/_b_a_c_k_e_n_d/Milestone/clinical/?(\?.*)?$':'MDC-API-CGP',
    r'^/_b_a_c_k_e_n_d/Milestone/ot/?(\?.*)?$':'MDC-API-OGP',
    r'^/_b_a_c_k_e_n_d/Milestone/speech/?(\?.*)?$':'MDC-API-SGP',
    r'^/_b_a_c_k_e_n_d/Milestone/physio/?(\?.*)?$':'MDC-API-PGP',
    r'^/_b_a_c_k_e_n_d/Milestone/assessment-analysis/?(\?.*)?$':'MDC-API-AGP',
    r'^/_b_a_c_k_e_n_d/Milestone/assessment-analysis/?(\?.*)?$':'MDC-P-AAU',

    # Goals
    '/_b_a_c_k_e_n_d/Milestone/goals/':'MDC-P-GOA',
    r'^/_b_a_c_k_e_n_d/Milestone/goals/.*$':'MDC-P-GOA',
    '/_b_a_c_k_e_n_d/Milestone/development-goals/':'MDC-P-GOA',
    r'^/_b_a_c_k_e_n_d/Milestone/development-goals/.*$':'MDC-P-GOA',
    '/_b_a_c_k_e_n_d/Milestone/goal-therapy-types/':'MDC-P-GOA',
    r'^/_b_a_c_k_e_n_d/Milestone/goal-therapy-types/.*$':'MDC-P-GOA',
    '/_b_a_c_k_e_n_d/Milestone/goal-domains/':'MDC-P-GOA',
    r'^/_b_a_c_k_e_n_d/Milestone/goal-domains/.*$':'MDC-P-GOA',
    '/_b_a_c_k_e_n_d/Milestone/goal-levels/':'MDC-P-GOA',
    r'^/_b_a_c_k_e_n_d/Milestone/goal-levels/.*$':'MDC-P-GOA',
    '/_b_a_c_k_e_n_d/Milestone/goal-libraries/':'MDC-P-GOA',
    r'^/_b_a_c_k_e_n_d/Milestone/goal-libraries/.*$':'MDC-P-GOA',

    '/_b_a_c_k_e_n_d/Milestone/all-assessments/':'',
    '/_b_a_c_k_e_n_d/Milestone/login/':'',
    '/_b_a_c_k_e_n_d/Milestone/developmental-tasks/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-assessments/':'',
    '/_b_a_c_k_e_n_d/Milestone/pediatric-assessment/':'',
    '/_b_a_c_k_e_n_d/Milestone/save-patient-skill/':'',
    '/_b_a_c_k_e_n_d/Milestone/pediatric_assessment_list/':'',
    '/_b_a_c_k_e_n_d/Milestone/reg_no/<str:prefix>/<str:id>/<str:year>/':'',
    '/_b_a_c_k_e_n_d/Milestone/all-patients/':'',
    '/_b_a_c_k_e_n_d/Milestone/employeeregistration/':'',
    '/_b_a_c_k_e_n_d/Milestone/save-mchat-response/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-mchat/<path:registration_number>/':'',
    '/_b_a_c_k_e_n_d/Milestone/developmental-screening-tasks/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-tasks/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-tasks/<str:patient_name>/':'',
    '/_b_a_c_k_e_n_d/Milestone/child_language_reports/':'',
    '/_b_a_c_k_e_n_d/Milestone/childspeechassessment/':'',
    '/_b_a_c_k_e_n_d/Milestone/CBCLgirlsassessment/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-cbcl/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-cbcl/<str:childName>/':'',
    '/_b_a_c_k_e_n_d/Milestone/oldtherapy-reports/?(\?.*)?$':'MDC-API-THR',

    #Leave Management

    '/_b_a_c_k_e_n_d/Milestone/submit-leave/':'MDC-API-L',
    '/_b_a_c_k_e_n_d/Milestone/get-pending-leaves/':'MDC-API-L',
    '/_b_a_c_k_e_n_d/Milestone/update-leave-status/':'MDC-API-L',
    r'^/_b_a_c_k_e_n_d/Milestone/get-leaves-report/?(\?.*)?$':'MDC-API-L',

    # Session Attendance
    
    '/_b_a_c_k_e_n_d/Milestone/session-attendance/load/?(\?.*)?$':'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/session-attendance/monthly-report/?(\?.*)?$':'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/session-attendance/slots/?(\?.*)?$':'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/session-attendance/save/?(\?.*)?$':'MDC-API-AT',
    '/_b_a_c_k_e_n_d/Milestone/session-attendance/underattended/?(\?.*)?$':'MDC-API-AT',

    #Appoinment Schedule

    '/_b_a_c_k_e_n_d/Milestone/get_dailytimeslot/':'MDC-P-GDTS',
    '/_b_a_c_k_e_n_d/Milestone/create_appointment/':'MDC-P-CA',
    '/_b_a_c_k_e_n_d/Milestone/get_all_therapists/':'MDC-P-GAT',
    r'/_b_a_c_k_e_n_d/Milestone/get_appointments_by_date/?(\?.*)?$':'MDC-P-GAD',
    '/_b_a_c_k_e_n_d/Milestone/update_appointment_status/':'MDC-P-UAS',
    r'/_b_a_c_k_e_n_d/Milestone/appointment_dashboard/?(\?.*)?$':'MDC-P-AD',

    #Enquiry form
    '/_b_a_c_k_e_n_d/Milestone/enquiryform/':'MDC-P-EF',
    r'/_b_a_c_k_e_n_d/Milestone/search_appointments/?(\?.*)?$':'MDC-P-CA',

    # Therapy
    '/therapy-reports/':'MDC-API-THR',
    '/get_patient_assessments/':'MDC-API-GAS',
    '/others-reports/':'MDC-API-RTS',
    '/get-latest-billing-no/':'MDC-API-LBN',
    '/get-consulting-doctors/':'MDC-API-CDR',
    '/save-consulting-doctor/':'MDC-P-ASM',
    '/save-assessments/':'MDC-P-ASM',
    '/others_billing/':'MDC-P-OSB',
    '/all-patient/':'MDC-API-PAT',
    '/pendingPayment/':'MDC-P-PNP',
    '/updatePayment/':'MDC-P-PNP',
    '/next-registration-number/':'MDC-P-REG',
    '/referral-doctor/list/':'MDC-P-REG',
    '/referral-doctor/register/':'MDC-P-REG',
    '/register/':'MDC-P-REG',
    '/referrals/':'MDC-P-SOR',
    '/therapy_billing/':'MDC-P-TRB',
     '/update-patient/?(\?.*)?$':'',
    '/update-doctor/?(\?.*)?$':'',
    '/update-employeeDr/?(\?.*)?$':'',
    '/all-assessments/':'',
    '/login/':'',
    '/developmental-tasks/':'',
    '/get-assessments/':'',
    '/pediatric-assessment/':'',
    '/save-patient-skill/':'',
    '/pediatric_assessment_list/':'',
    '/reg_no/<str:prefix>/<str:id>/<str:year>/':'',
    '/all-patients/':'',
    '/employeeregistration/':'',
    '/save-mchat-response/':'',
    '/get-mchat/<path:registration_number>/':'',
    '/developmental-screening-tasks/':'',
    '/get-tasks/':'',
    '/get-tasks/<str:patient_name>/':'',
    '/child_language_reports/':'',
    '/childspeechassessment/':'',
    '/CBCLgirlsassessment/':'',
    '/get-cbcl/':'',
    '/get-cbcl/<str:childName>/':'',
}
PAGE_ACTION_MAPPING = {
    'xxx': {
        'DELETE':'RWD',
    },
}
GEN_ACTION_MAPPING = {
    'POST': 'RW',
    'PUT': 'RW',
    'DELETE': 'RW',
    'PATCH': 'RW',
    'GET': 'R',
}
