PAGE_MAPPING = {
    '/_b_a_c_k_e_n_d/Milestone/therapy-reports/?(\?.*)?$':'MDC-API-THR',
    '/_b_a_c_k_e_n_d/Milestone/get_patient_assessments/?(\?.*)?$':'MDC-API-GAS',
    '/_b_a_c_k_e_n_d/Milestone/others-reports/?(\?.*)?$':'MDC-API-RTS',   
    '/_b_a_c_k_e_n_d/Milestone/get-latest-billing-no/':'MDC-API-LBN',
    '/_b_a_c_k_e_n_d/Milestone/get-consulting-doctors/':'MDC-API-CDR',
    '/_b_a_c_k_e_n_d/Milestone/save-consulting-doctor/':'MDC-P-ASM',
    '/_b_a_c_k_e_n_d/Milestone/save-assessments/':'MDC-P-ASM',
    '/_b_a_c_k_e_n_d/Milestone/others_billing/':'MDC-P-OSB',
    '/_b_a_c_k_e_n_d/Milestone/all-patient/?(\?.*)?$':'MDC-API-PAT',
    '/_b_a_c_k_e_n_d/Milestone/pendingPayment/':'MDC-P-PNP',
    '/_b_a_c_k_e_n_d/Milestone/updatePayment/':'MDC-P-PNP',
    '/_b_a_c_k_e_n_d/Milestone/next-registration-number/':'MDC-P-REG',
    '/_b_a_c_k_e_n_d/Milestone/referral-doctor/list/':'MDC-API-RDL',
    '/_b_a_c_k_e_n_d/Milestone/referral-doctor/register/':'MDC-P-REG',
    '/_b_a_c_k_e_n_d/Milestone/register/':'MDC-P-REG',   
    '/_b_a_c_k_e_n_d/Milestone/referrals/?(\?.*)?$':'MDC-P-SOR',
    '/_b_a_c_k_e_n_d/Milestone/therapy_billing/':'MDC-P-TRB',
    '/_b_a_c_k_e_n_d/Milestone/update-patient/?(\?.*)?$':'MDC-P-PTE',
    '/_b_a_c_k_e_n_d/Milestone/update-doctor(?:/[^/]+)+/$':'MDC-P-RDE',
    '/_b_a_c_k_e_n_d/Milestone/update-employeeDr(?:/[^/]+)+/$':'MDC-P-CDE',

    '/_b_a_c_k_e_n_d/Milestone/all-assessments/':'',
    '/_b_a_c_k_e_n_d/Milestone/login/':'',
    '/_b_a_c_k_e_n_d/Milestone/developmental-tasks/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-assessments/':'',
    '/_b_a_c_k_e_n_d/Milestone/pediatric-assessment/':'',
    '/_b_a_c_k_e_n_d/Milestone/save-patient-skill/':'',
    '/_b_a_c_k_e_n_d/Milestone/pediatric_assessment_list/':'',
    '/_b_a_c_k_e_n_d/Milestone/reg_no/<str:prefix>/<str:id>/<str:year>/':'',
    '/_b_a_c_k_e_n_d/Milestone/all-patients/':'',    
    '/_b_a_c_k_e_n_d/Milestone/employeeregistration/':'',
    '/_b_a_c_k_e_n_d/Milestone/save-mchat-response/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-mchat/<path:registration_number>/':'',
    '/_b_a_c_k_e_n_d/Milestone/developmental-screening-tasks/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-tasks/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-tasks/<str:patient_name>/':'',
    '/_b_a_c_k_e_n_d/Milestone/child_language_reports/':'',
    '/_b_a_c_k_e_n_d/Milestone/childspeechassessment/':'',
    '/_b_a_c_k_e_n_d/Milestone/CBCLgirlsassessment/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-cbcl/':'',
    '/_b_a_c_k_e_n_d/Milestone/get-cbcl/<str:childName>/':'',

    '/therapy-reports/':'MDC-API-THR',
    '/get_patient_assessments/':'MDC-API-GAS',
    '/others-reports/':'MDC-API-RTS',   
    '/get-latest-billing-no/':'MDC-API-LBN',
    '/get-consulting-doctors/':'MDC-API-CDR',
    '/save-consulting-doctor/':'MDC-P-ASM',
    '/save-assessments/':'MDC-P-ASM',
    '/others_billing/':'MDC-P-OSB',
    '/all-patient/':'MDC-API-PAT',
    '/pendingPayment/':'MDC-P-PNP',
    '/updatePayment/':'MDC-P-PNP',
    '/next-registration-number/':'MDC-P-REG',
    '/referral-doctor/list/':'MDC-P-REG',
    '/referral-doctor/register/':'MDC-P-REG',
    '/register/':'MDC-P-REG',   
    '/referrals/':'MDC-P-SOR',
    '/therapy_billing/':'MDC-P-TRB',
     '/update-patient/?(\?.*)?$':'',
    '/update-doctor/?(\?.*)?$':'',
    '/update-employeeDr/?(\?.*)?$':'',


    '/all-assessments/':'',
    '/login/':'',
    '/developmental-tasks/':'',
    '/get-assessments/':'',
    '/pediatric-assessment/':'',
    '/save-patient-skill/':'',
    '/pediatric_assessment_list/':'',
    '/reg_no/<str:prefix>/<str:id>/<str:year>/':'',
    '/all-patients/':'',    
    '/employeeregistration/':'',
    '/save-mchat-response/':'',
    '/get-mchat/<path:registration_number>/':'',
    '/developmental-screening-tasks/':'',
    '/get-tasks/':'',
    '/get-tasks/<str:patient_name>/':'',
    '/child_language_reports/':'',
    '/childspeechassessment/':'',
    '/CBCLgirlsassessment/':'',
    '/get-cbcl/':'',
    '/get-cbcl/<str:childName>/':'',
}

PAGE_ACTION_MAPPING = {
    'xxx': {
        'DELETE':'RWD',
    },
}

GEN_ACTION_MAPPING = {
    'POST': 'RW',
    'PUT': 'RW',
    'DELETE': 'RW',
    'PATCH': 'RW',
    'GET': 'R',
}