from django.urls import path, re_path
from . import views 
from .views import pediatric_assessment_list,get_patients_report
from .Views import Security ,patientdetails ,cbcl,consultingdoctors,invoice,referals,mchat,therapybilling,childlanguage,developmentalscreeningtask, Others,pediatricassessment, attendance, Assessment , goals, leave, developmentgoals, goalsmaster, sessionattendance, appoinmentschedule, notification

urlpatterns = [
    path('notifications/create/', notification.create_notification, name='create_notification'),
    path('notifications/send/', notification.mark_notification_sent, name='mark_notification_sent'),
    path('notifications/list/', notification.get_notifications, name='get_notifications'),
    path('notifications/mark-read/', notification.mark_notification_read, name='mark_notification_read'),
    path('notifications/report/', notification.get_notification_report, name='get_notification_report'),
    path('notifications/<str:pk>/', notification.delete_notification, name='delete_notification'),
    path('therapy-reports/', therapybilling.get_therapy_reports, name='therapy-reports'),
    path('get_patient_assessments/', views.get_patient_assessments, name='get_patient_assessments'),
    path('others-reports/', Others.get_others_reports, name='get_others_reports'),
    path('get-latest-billing-no/', invoice.get_latest_billing_no,name='get_latest_billing_no'),
    path('get-consulting-doctors/', consultingdoctors.get_consulting_doctors, name='get_consulting_doctors'),
    path('save-consulting-doctor/', consultingdoctors.save_consulting_doctor, name='save_consulting_doctor'),
    path('save-assessments/', patientdetails.save_assessments, name='save-assessments'), 
    path('others_billing/', Others.others_billing, name='others_billing'),  
    path('all-patient/', patientdetails.get_all_patients, name='all-patients'),
    path('all-patient-filterless/', patientdetails.get_all_patients_filterless, name='get_all_patients_filterless'),
    path('all-attendance-patient/', attendance.get_all_attendance_patients, name='all-patients'),
    path('pendingPayment/', invoice.pendingPayment, name='pendingPayment'),
    path('updatePayment/', invoice.update_payment, name='update_payment'),
    path('next-registration-number/', patientdetails.get_latest_registration_number, name='next_registration_number'),
    path("referral-doctor/list/", referals.get_referral_doctors, name="list-referral-doctors"),
    path("referral-doctor/register/", referals.register_referral_doctor, name="register-referral-doctor"),
    path('register/', patientdetails.create_registration, name='register'),      
    path('referrals/', patientdetails.get_referrals, name='get_referrals'),  
    path('therapy_billing/', therapybilling.therapy_billing, name='therapy_billing'),  
    re_path(r'^update-patient/(?P<registration_number>MDC/\d+/\d+)/$', patientdetails.update_registration, name='update_registration'), 
    path('update-doctor/<str:referral_id>/', referals.update_doctor, name='update_doctor'),     
    path('update-employeeDr/<str:employee_id>/', consultingdoctors.update_consulting_doctor, name='update_consulting_doctor'), 
    path('get_all_patient_details/', patientdetails.get_all_patient_details, name='get_all_patient_details'),
    path('attendance/', attendance.add_patient_attendance, name='add_attendance'),     
    
    path('all-assessments/', patientdetails.get_all_assessments, name='all-assessments'),     
    path('developmental-tasks/', developmentalscreeningtask.DevelopmentalTask, name='DevelopmentalTask'),
    path('get-assessments/',patientdetails.get_assessments, name='get-assessments'),
    path('pediatric-assessment/',views.PediatricAssessment, name='pediatric-assessment'),
    path('save-patient-skill/', views.save_patient_skilltest, name='save-patient-skill'),
    path('pediatric_assessment_list/', pediatric_assessment_list, name='pediatric_assessment_list'),
    path('reg_no/<str:prefix>/<str:id>/<str:year>/', patientdetails.get_patient_by_registration, name='get_patient_by_registration'),
    path('all-patients/', get_patients_report, name='pediatric_assessment_list'),
    path('employeeregistration/', Security.employeeregistration,name='employeeregistration'),
    path('save-mchat-response/', mchat.saveMCHATResponses, name='save-mchat-response'),
    path('get-mchat/<path:registration_number>/', mchat.getMCHATResponse, name='get-mchat-response'),
    path('developmental-screening-tasks/', developmentalscreeningtask.save_developmental_screening_tasks, name='save_developmental_screening_tasks'),
    path('get-tasks/', developmentalscreeningtask.get_developmental_screening_tasks, name='get_tasks'),
    path('get-tasks/<str:patient_name>/', developmentalscreeningtask.get_developmental_screening_tasks, name='get_tasks_by_patient'),   
    path('child_language_reports/', childlanguage.get_childlanguage_reports, name='get_childlanguage_reports'),
    path('childspeechassessment/', childlanguage.child_language_assessment, name='child_language_assessment'),
    path('CBCLgirlsassessment/', cbcl.submit_cbcl, name='submit_cbcl'),
    path('get-cbcl/', cbcl.get_cbcl_data, name='get_all_cbcl'),
    path('get-cbcl/<str:childName>/', cbcl.get_cbcl_data, name='get_cbcl_by_patient'),
    path('pending-payments/', therapybilling.pending_payment_report, name='pending-payments'),
    path('get_all_patient_attendance/', attendance.get_all_patient_attendance, name='get_all_patient_attendance'),
    path('patient-month-session-counts/', attendance.get_patient_month_session_counts, name='patient_month_session_counts'),
    path('therapy-details/', attendance.get_therapy_details, name='therapy-details'),
    # path('edit_patient_attendance/', patientdetails.edit_patient_attendance, name='edit_patient_attendance'),
    # path('delete_patient_attendance/', patientdetails.delete_patient_attendance, name='delete_patient_attendance'),
    path("get_pending_attendance_requests/", attendance.get_pending_attendance_requests, name="update_attendance_by_reg_and_date"),

    path("attendance-update/", attendance.update_attendance_by_reg_and_date, name="update_attendance_by_reg_and_date"),
    path("HistoryRecordingSheet/", pediatricassessment.CreateHistoryRecordingSheet, name="HistoryRecordingSheet"),
    path("GetHistoryRecordingSheet/", pediatricassessment.GetHistoryRecordingSheet, name="GetHistoryRecordingSheet"),
    path("GetHistoryRecordingSheetbyRegNO/",pediatricassessment.GetHistoryRecordingSheetbyRegNO, name="GetHistoryRecordingSheetbyRegNO"),

    path("UpdateHistoryRecordingSheet/", pediatricassessment.UpdateHistoryRecordingSheet, name="UpdateHistoryRecordingSheet"),

    path("update_attendance_sessions/", attendance.update_attendance_sessions, name="update_attendance_sessions"),

    path('get_all_patient_oldattendance/', attendance.get_all_patient_oldattendance, name='get_all_patient_oldattendance'),
    
    path('oldtherapy-reports/', therapybilling.get_oldtherapy_reports, name='oldtherapy-reports'),

    path("get_ot_patients/", Assessment.get_ot_patients),
    path("get_speech_patients/", Assessment.get_speech_patients),
    path("get_pt_patients/", Assessment.get_pt_patients),
    path("get_psychological_patients/", Assessment.get_psychological_patients),
    path("get_all_category_patients/", Assessment.get_all_category_patients),
    path('clinical/', Assessment.clinical_psychology_assessment),
    path('behavioral-observation-options/', Assessment.behavioral_observation_options),
    path('ot/', Assessment.occupational_therapy_assessment),
    path('speech/', Assessment.speech_therapy_assessment),
    path('physio/', Assessment.physiotherapy_assessment),
    path("assessment-analysis/", Assessment.assessment_analysis_list_create),
    path("assessment-analysis/<int:pk>/", Assessment.assessment_analysis_detail),
    
    path("goals/", goals.goals_assessment_list_create),
    path('goals/<str:pk>/', goals.goals_assessment_update),
    path("goals/<int:pk>/image/<str:image_id>/", goals.delete_goal_image),
    path("goals/image/<str:image_id>/", goals.view_goal_image),
    path("goals/file/<str:file_id>/", goals.view_goal_file),
    
    path("submit-leave/", leave.submit_leave, name="submit_leave"),
    path("get-pending-leaves/", leave.get_pending_leaves, name="get_pending_leaves"),
    path("update-leave-status/", leave.update_leave_status, name="update_leave_status"),
    path("get-leaves-report/", leave.get_leaves_report, name="get_leaves_report"),

    
    path("development-goals/", developmentgoals.development_goals_list_create, name="development_goals_list_create"),
    path("development-goals/<str:pk>/", developmentgoals.development_goals_detail, name="development_goals_detail"),

    # Goals Master Data
    path('goal-therapy-types/', goalsmaster.therapy_type_list_create, name='therapy_type_list_create'),
    path('goal-therapy-types/<str:pk>/', goalsmaster.therapy_type_detail, name='therapy_type_detail'),
    path('goal-domains/', goalsmaster.domain_list_create, name='domain_list_create'),
    path('goal-domains/<str:pk>/', goalsmaster.domain_detail, name='domain_detail'),
    path('goal-levels/', goalsmaster.level_list_create, name='level_list_create'),
    path('goal-levels/<str:pk>/', goalsmaster.level_detail, name='level_detail'),
    path('goal-libraries/', goalsmaster.goal_library_list_create, name='goal_library_list_create'),
    path('goal-libraries/<str:pk>/', goalsmaster.goal_library_detail, name='goal_library_detail'),
    path('activity-libraries/', goalsmaster.activity_library_list_create, name='activity_library_list_create'),
    path('activity-libraries/<str:pk>/', goalsmaster.activity_library_detail, name='activity_library_detail'),

    # Session Attendance
    path('session-attendance/slots/', sessionattendance.get_active_slots, name='session_attendance_slots'),
    path('session-attendance/load/', sessionattendance.load_session_attendance, name='session_attendance_load'),
    path('session-attendance/save/', sessionattendance.save_session_attendance, name='session_attendance_save'),
    path('session-attendance/confirm/', sessionattendance.confirm_session_attendance, name='session_attendance_confirm'),
    path('session-attendance/underattended/', sessionattendance.get_underattended_patients, name='session_attendance_underattended'),
    path('session-attendance/monthly-report/', sessionattendance.get_monthly_attendance_report, name='session_attendance_monthly_report'),

    #Appoinment Schedule
    path('get_dailytimeslot/', appoinmentschedule.get_dailytimeslot, name='get_dailytimeslot'),
    path('create_appointment/', appoinmentschedule.create_appointment, name='create_appointment'),
    path('get_all_therapists/', appoinmentschedule.get_all_therapists, name='get_all_therapists'),
    path('get_appointments_by_date/', appoinmentschedule.get_appointments_by_date, name='get_appointments_by_date'),
    path('update_appointment_status/', appoinmentschedule.update_appointment_status, name='update_appointment_status'),
    path('appointment_dashboard/', appoinmentschedule.appointment_dashboard, name='appointment_dashboard'),
    path('search_appointments/', appoinmentschedule.search_appointments, name='search_appointments'),
    path('appointment-report/', appoinmentschedule.appointment_report, name='appointment_report'),

    #Enquiry form
    path('enquiryform/', appoinmentschedule.enquiryform, name='enquiryform'),
]
