# Generated by Django 3.2.12 on 2026-05-20 07:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentGoals',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('development_goals', djongo.models.fields.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalDomain',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('therapy_type', models.CharField(max_length=100)),
                ('domain_no', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalLevel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalLibrary',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('goal_name', models.TextField()),
                ('goal_no', models.CharField(blank=True, max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('therapy_type', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TherapyDetails',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('therapy_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'milestone_backend_therapydetails',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historyrecordingsheet',
            name='presenting_complaints',
            field=djongo.models.fields.JSONField(),
        ),
        migrations.CreateModel(
            name='leaveform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('leave_date', models.DateField()),
                ('leave_reason', models.TextField(blank=True, null=True)),
                ('leave_status', models.CharField(default='Pending', max_length=50)),
                ('leave_approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('leave_approved_date', models.DateField(blank=True, null=True)),
                ('leave_reject_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'milestone_backend_leaveform',
                'unique_together': {('registration_number', 'leave_date')},
            },
        ),
    ]
