# Generated by Django 3.2.12 on 2026-06-30 11:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0002_auto_20260520_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='goallevel',
            name='level_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='goallibrary',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physiotherapyassessment',
            name='gross_development',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='physiotherapyassessment',
            name='long_term_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physiotherapyassessment',
            name='reflexes',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='physiotherapyassessment',
            name='short_term_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='therapydetails',
            name='therapy_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
