# Generated by Django 3.2.12 on 2026-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0003_auto_20260630_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalpsychologyassessment',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='occupationaltherapyassessment',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physiotherapyassessment',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='speechtherapyassessment',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
