# Generated by Django 3.2.12 on 2026-07-02 04:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0004_auto_20260701_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeSlot',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('slot_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('sequence', models.IntegerField()),
                ('is_break', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'milestone_backend_dailytimeslot',
            },
        ),
        migrations.CreateModel(
            name='PatientSessionAttendance',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
                ('therapy_id', models.CharField(max_length=50)),
                ('therapy_name', models.CharField(max_length=150)),
                ('attended_slot', models.CharField(max_length=50)),
                ('slot_label', models.CharField(max_length=100)),
                ('sessions_attended', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'milestone_backend_patientsessionattendance',
            },
        ),
    ]
