# Generated by Django 3.2.12 on 2026-07-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0005_dailytimeslot_patientsessionattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsessionattendance',
            name='therapist',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
