# Generated by Django 3.2.12 on 2026-07-03 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0006_patientsessionattendance_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('name_of_child', models.CharField(max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('therapist_id', models.CharField(max_length=100)),
                ('rescheduled_therapist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_datetime', models.DateTimeField()),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('isactive', models.BooleanField(default=True)),
                ('status', models.CharField(default='Scheduled', max_length=200)),
                ('cancel_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cancelled_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patientsessionattendance',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
