# Generated by Django 3.2.12 on 2026-07-06 11:34

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0007_auto_20260703_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLibrary',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('task_name', models.TextField()),
                ('task_id', models.CharField(blank=True, max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('therapy_type', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'milestone_backend_activitylibrary',
            },
        ),
    ]
