# Generated by Django 3.2.12 on 2026-07-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0008_activitylibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapydetails',
            name='color',
            field=models.CharField(blank=True, default='#406147', max_length=50, null=True),
        ),
    ]
