# Generated by Django 3.2.12 on 2026-07-08 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0010_rename_sensory_evaluation_occupationaltherapyassessment_sensory_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('enquiry_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name_of_child', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('address', models.TextField()),
                ('problem', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='enquiry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
