# Generated by Django 3.2.12 on 2026-07-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0011_auto_20260708_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
