# Generated by Django 3.2.12 on 2026-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_backend', '0012_registration_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralObservationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
